version: "3.9"
services:
  garage-api:
    image: liorelb/x-garage-api
    environment:
      GARAGE_MONGO_HOST: mongo
      GARAGE_MONGO_PORT: 27017
    ports:
      - "8000:80"
  mongo:
    image: mongo